name: linkedinbot
description: "LinkedIn Connection Bot"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  window_manager: ^0.3.7
  flutter_riverpod: ^2.4.9
  google_fonts: ^6.2.0

flutter:
  uses-material-design: true

  assets:
     - assets/